--- # Program to test create_folder_tableau
- hosts: web_servers
  become: yes
  #become_method: runas
  gather_facts: no
  vars:
    api_key: "'{{ lookup('env', 'VM_PASSWORD') }}'"
  tasks:
    - name: Basic usage
      debug:
        msg: "'{{ lookup('env', 'VM_PASSWORD') }}'"

    - name: Insert multiple lines and Backup sasauth file
      blockinfile:
        path: /home/ec2-user/test/test.txt
        create: yes
        block: |
          test "{{ api_key }}"