---

- name: Create New user on Windows Machine

  hosts: windows2016

  tasks:   

    - name: Create a new User 

      win_user:

        name: 'Juver'

        password: '{{ansible_ssh_pass}}'

        state: present

        groups:

          - Users
      when: ansible_os_family == 'Windows'
