---
- name: create a new dir on C
  hosts: servers
  become: True
  become_method: runas
  gather_facts: no
  vars:
    ansible_become_user: "{{ ansible_user }}"
    ansible_become_pass: "{{ ansible_password }}"
  tasks:
  - import_role:
      name: "new_dir"
    tags:
      - new_dir